### ISSUE TITLE
Update to create-react-app v3.3.1 when it is available

### ISSUE THREAD

**Issue by andrewcottam** [marxanweb/general#119]
react-scripts 3.3.0 has a bug which prevents the marxan-client from running in dev mode (see here - https://github.com/facebook/create-react-app/issues/8075) and so any developers who fork marxan-client wont be able to run it. As soon as v3.3.1 is available (which contains the bug fix see here - https://github.com/facebook/create-react-app/pull/8079) add it to the marxan-client package.json file.

**Comment by marxanweb** [comment]
3.3.1 released on 30 Jan https://github.com/facebook/create-react-app/releases/tag/v3.3.1
To upgrade:
```
npm install --save --save-exact react-scripts@3.3.1
```

**Comment by marxanweb** [comment]
I installed the latest version of react-scripts on the dev machine
```
npm install react-scripts --save
```
