### ISSUE TITLE
cost surfaces for training modules

### ISSUE THREAD

**Issue by jamcgowan-SCP** [marxanweb/general#226]
BC example needs a cost surface with equal area  ( how do you envision the different cost surfaces here? ) I suppose having the option to select via a radial button or click box in the PU tab to select either equal area or human uses cost would be sensible. 

We need to add the BC equal area cost, and create a cost surface for Tonga ( I can look into it).

**Comment by andrewcottam** [comment]
Done - I'll document how to create costs surfaces in the help
